=head1 NAME

tpm - tiny password manager

=head1 SYNOPSIS

B<tpm> I<COMMAND> [I<ENTRY>|I<GROUP>]

=head1 DESCRIPTION

tpm is a tiny shell script which is heavily inspired and largely
compatible with pass(1). Just like pass it uses gpg2(1) to securely
store your passwords, the major difference between pass and tpm is that
the latter is a lot more minimal. Furthermore, tpm is written entirely
in POSIX shell.

Adding, removing or showing a password is done by invoking tpm with the
I<insert>, I<remove> or I<show> command respectively followed by a
name. tpm will then prompt for a password or confirmation before it
modifies or shows the corresponding entry.

When using the I<show> command, globbing is allowed to avoid typing
potentially long entry paths. In case multiple entries match, tpm exits
without showing any password but a warning instead.

tpm I<help> prints information about how to use tpm.

tpm simply stores everything in a directory structure where passwords
correspond to individually PGP encrypted files, optionally residing
inside nested subdirectories of arbitrary depth, where any subdirectory
can be interpreted as a (sub)group to manage large collections easily.

This allows for transparent integration with B<git> for example to keep
track of changes and/or add comments while editing passwords.

tpm I<list> followed by a directory path, that is a group name, lists
all entries inside the specified group as well as all its subgroups.

=head1 ENVIRONMENT

=over 4

=item B<PASSWORD_STORE_DIR>

The storage directory (default: ~/.tpm/).

=item B<PASSWORD_STORE_KEY>

GPG key to encrypt files with (default: self).

=back

=head1 FILES

=over 4

=item I<~/.tpm/>

The default storage directory.

=back

=head1 EXAMPLES

Create a new entry with a random password using pwgen(1):

	$ pwgen -1 | tpm insert system/new-user

Create a new entry called 'system/root':

	$ tpm insert system/root

Write your 'system/root' password to standard output:

	$ tpm show system/root

Write the entry's password that matches the given pattern to standard
output:

	$ tpm show em/r*t
	$ tpm show root

Copy your 'system/root' password to the clipboard using xclip(1):

	$ tpm show system/root | tr -d '\n' | xclip

List all entries of the group 'system':

	$ tpm list system

=head1 SEE ALSO

git(1), gpg2(1), pwgen(1), xclip(1)
