.Dd March 22, 2017
.Dt SPM 1
.Os
.Sh NAME
.Nm spm
.Nd simple password manager
.Sh SYNOPSIS
.Nm Cm add Oo Ar group/ Oc Ns Ar name
.Nm Cm del Ar expression
.Nm Cm list Oo Fl g Oc Op Ar group
.Nm Cm search Ar expression
.Nm Cm show Ar expression
.Sh DESCRIPTION
.Nm
is a single fully POSIX shell compliant script using
.Xr gpg2 1
for encryption.
.sp
Entries are stored in a classical filesystem hierarchy where passwords
are encrypted as individual files and directories may be used as groups.
This enables users to control access through file ownership, manage
shared password with symbolic links and more just like any other files.
.sp
Command line agruments, that is group and entry paths, are considered to
be relative to the storage root. Except when creating or listing
entries,
.Ar expression
is expected to be a basic regular expression as defined in
.Xr re_format 7 .
This is not only helpful but also required to provide means of
distinguishing ambigious entry names. The following commands are
available:
.Bl -tag -width Ds
.It Cm add
Prompt for a password if standard output is a terminal otherwise read
from standard input and store it as entry
.Ar name .
If
.Ar name
contains forward slashes, the entry is put within the respective group.
Non-existing groups are created automatically.
.It Cm del
Ask for confirmation and delete the entry matching
.Ar expression
on success.
.It Cm list
Print a recursive, indented tree-style list of all entries in group
.Ar group
If the
.Fl g
flag is passed only subgroups are shown. If
.Ar group
is omitted, the entire storage root is listed.
.It Cm search
Print the absoloute paths of all entries matching
.Ar expression
one per line.
.It Cm show
Print the password to standard output if
.Ar expression
uniquely matches an entry and prompt for the decryption passphrase if
it is not cached by
.Xr gpg-agent 1 .
.El
.Sh ENVIRONMENT
The following environment variables will be used by
.Nm
if they are set and not empty:
.Bl -tag -width Ds
.It Ev PASSWORD_STORE_DIR
The storage root directory. This should be an absoloute path.
.It Ev PASSWORD_STORE_KEY
Key ID used for de/encryption. Refer to
.Xr gpg2 1
for accepted formats.
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa ~/.spm/
The default storage root directory.
.El
.Sh EXIT STATUS
.Ex
.Sh EXAMPlES
Add Alice's password to the group
.Em users :
.Bd -literal -offset indent
$ spm add users/alice
Password for 'users/alice':
.Ed
.sp
Make sure she is an admin as well:
.Em 
.Bd -literal -offset indent
$ (cd ~/.spm
> mkdir admins
> ln -s ../members/alice admins/alice)
.Ed
.sp
Copy her password into the X selection ready to be pasted somewhere:
.Bd -literal -offset indent
$ spm show admins/alice | xclip -i
.Ed
.sp
Find all admins starting with
.Dq a
or
.Dq b :
.Bd -literal -offset indent
$ spm search admins/[ab]
/home/alice/.spm/admins/alice
/home/alice/.spm/admins/bob
.Ed
.sp
List all users:
.Bd -literal -offset indent
$ spm list users
/home/alice/.spm/users
|-- alice
|-- bob
|-- temporary/
|   |-- tim
|   `-- tom
.Ed
.Sh SEE ALSO
.Xr gpg2 1 ,
.Xr gpg-agent 1 ,
.Xr tpm 1 ,
.Xr tree 1 ,
.Xr re_format 7
.Sh AUTHORS
.Nm
is written by
.An Klemens Nanni Aq Mt kl3@posteo.org .
